Patching FindGaudi.cmake, and making the ReleaseData generation a little smarter (AtlasCMake-00-01-54)
	* Turned off the automatic documentation generation once again.
	* Tried to make FindGaudi.cmake pick up the correct version of
	  Gaudi for the RPM name generation in the nightly. The proper
	  fix for this will be to generate a text file in the Gaudi build
	  that FindGaudi.cmake will be able to use to get this version
	  number.
	* Made the ReleaseData file generation a little smarter. Making
	  use of a few more NICOS environment variables than it did
	  before. (Made sure that the file would still look reasonable
	  when generating it outside of NICOS.)
	* Tagging as AtlasCMake-00-01-54

2016-06-02 Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
	* Updated Doxygen to create many subdirectories for its
	  documentation. As AFS can not deal with a single directory
	  layout.
	* Moved the tag file into the doc/ subdirectory in the installation
	  tree.
	* Declared an installation rule for the documentation files.
	* Turned on the default build of the "doc" target once again. As
...
(Long ChangeLog diff - truncated)


Former-commit-id: 081a0df6262f4378e1fe07bf0dd694c7f4c6f294

diff --git a/Build/AtlasCMake/modules/scripts/atlas_ctest.sh.in b/Build/AtlasCMake/modules/scripts/atlas_ctest.sh.in
--- a/Build/AtlasCMake/modules/scripts/atlas_ctest.sh.in
+++ b/Build/AtlasCMake/modules/scripts/atlas_ctest.sh.in
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# $Id: atlas_ctest.sh.in 725483 2016-02-22 12:38:45Z krasznaa $
+# $Id: atlas_ctest.sh.in 749821 2016-05-26 09:52:35Z krasznaa $
 #
 # This is a custom wrapper around the ctest command, to enable us to
 # capure the full build log of the individual packages.
@@ -56,5 +56,12 @@ echo "# CMake ---> $*" >> ${LOG_DIR}/${LOG_FILE}
 # to the specified log file. Note that the exit status of the actual command
 # is not in $? in the end. As that's populated by the exit status of the tee
 # command...
-@CMAKE_CTEST_COMMAND@ ${CMD_LINE_ARGS} 2>&1 | tee -a ${LOG_DIR}/${LOG_FILE}; \
-    test ${PIPESTATUS[0]} -eq 0
+@CMAKE_CTEST_COMMAND@ ${CMD_LINE_ARGS} 2>&1 | tee -a ${LOG_DIR}/${LOG_FILE}
+
+# Check if the command succeeded:
+returnCode=${PIPESTATUS[0]}
+if [ ${returnCode} != 0 ]; then
+    echo "error: Failed to execute $* (return code: ${returnCode})" \
+        >> ${LOG_DIR}/${LOG_FILE}
+    exit ${returnCode}
+fi
