Update packages:VP1Algs VP1AlgsBatch VP1AlgsEventProd VP1Base VP1Gui VP1HEPVis VP13DCocktailPlugin VP1AODPlugin VP1GeometryPlugin VP12DGeometrySystems VP1AODSystems VP1BPhysSystems VP1CaloClusterSystems VP1CaloReadoutSystems VP1CaloSystems VP1GeometrySystems VP1GuideLineSystems VP1LegoSystems VP1MCSystems VP1MissingEtSystems VP1PRDSystems VP1RawDataSystems VP1SimHitSystems VP1TestSystems VP1TrackSystems VP1TrackingGeometrySystems VP1TriggerDecisionSystems VP1TriggerSystems VP1UtilitySystems VP1VertexSystems VP1TrkAuxAlgs VP1Utils VP1UtilsBase  from upstream/master to upstream/21.9 via pseudo-merge
Former-commit-id: 6c5f9e14b5614ae60c08fba3853df8b964742e3e

diff --git a/graphics/VP1/VP1Algs/share/vp1 b/graphics/VP1/VP1Algs/share/vp1
--- a/graphics/VP1/VP1Algs/share/vp1
+++ b/graphics/VP1/VP1Algs/share/vp1
@@ -4,14 +4,37 @@
 #
 # Author: Thomas.Kittelmann@cern.ch
 # First useful version: July 2007
+#
 # Modified: Manuel.Proissl@cern.ch, March 2012
 #           Riccardo.Maria.Bianchi@cern.ch, multiple times
 #           Edward.Moyse@cern.ch, multiple times
 #
+# Current Maintainers: 
+#           - Riccardo.Maria.Bianchi@cern.ch
+#           - Edward.Moyse@cern.ch
 #
 # Questions: Riccardo.Maria.Bianchi@cern.ch
 #
 #
+
+
+#fixme/todo: option to start cruise mode (event/second)
+#fixme/todo: MULTINP_CPY should not be allowed to exist beforehand!
+
+
+### TERMINAL COLORS ###
+GREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+LIGHTBLUE='\033[1;34m'
+RED='\033[0;31m'
+WHITE='\033[0;97m'
+UNDERLINED='\033[4m'
+BOLD='\033[1m'
+NC='\033[0m' # No Color
+# then use:
+# - printf "I ${RED}love${NC} Stack Overflow\n"
+# - echo -e "I ${RED}love${NC} Stack Overflow"
+
 
 
 echo
@@ -30,13 +53,30 @@ echo
 # https://its.cern.ch/jira/browse/ATLASVPONE-228 #
 #                                                #
 ##################################################
-echo "*** VP1 NOTE *** setting LD_PRELOAD=/usr/lib64/libGL.so.1 env var, to correctly load OpenGL before all other TLS libs. That is caused by a bug in Red Hat 6. For details, see: https://its.cern.ch/jira/browse/ATLASVPONE-228"
+echo -e "${LIGHTBLUE}*** VP1 NOTE ***${NC} setting LD_PRELOAD=/usr/lib64/libGL.so.1 env var, to correctly load OpenGL before all other TLS libs. That is caused by a bug in Red Hat 6. For details, see: https://its.cern.ch/jira/browse/ATLASVPONE-228"
 export LD_PRELOAD=/usr/lib64/libGL.so.1
 ##################################################
 
+##################################################
+# Workaraound for keyboard input issue on LXPLUS #
+#                                                #
+# Details:                                       #
+# https://its.cern.ch/jira/browse/ATLASVPONE-380 #
+#                                                #
+##################################################
+if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+    # We are on a GNU/Linux platform machine
+    if [[ $(hostname) == lxplus* ]]; then
+        # We are on a LXPLUS machine
+        echo "uname: " "$(expr substr $(uname -s) 1 5)"
+        echo "hostname: " "$(hostname)"
+        echo -e "${LIGHTBLUE}*** VP1 NOTE ***${NC} you are running VP1 remotely on a LXPLUS machine. Hence, we set the 'QT_XKB_CONFIG_ROOT environment variable to fix the problem LXPLUS machine have with the new Qt5 framework, which prevent a proper detection of keyboard events. For details, see: https://its.cern.ch/jira/browse/ATLASVPONE-380."
+        export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
+    fi # closes "lxplus"
+fi # closes "Linux"
+##################################################
 
-#fixme/todo: option to start cruise mode (event/second)
-#fixme/todo: MULTINP_CPY should not be allowed to exist beforehand!
+
 
 APP=`basename $0`
 
@@ -45,6 +85,30 @@ if [ $? != 0 ]; then
     echo "Error: athena.py not found in path. Please setup atlas release before running"
     exit 1
 fi
+
+
+#######################################
+##         Warning Messages          ##
+#######################################
+MUSTQUIT=0
+if [ -z ${Athena_VERSION+x} ]; then
+    echo "ERROR! The variable 'Athena_VERSION' is unset! Apparently Athena is not properly set. Quitting..."
+    MUSTQUIT=1
+else
+    if [[ ${Athena_VERSION} =~ ^21\. ]]; then
+        echo; echo -e " ${RED}${BOLD}   *** WARNING! Release 21 detected! *** ${NC}"; echo
+        echo -e "   Apparently, you are using the Release 21 of the Athena environment. Unfortunately, VP1 does not work in rel. 21. ${UNDERLINED}Please use a release >= 22, or the 'master' release${NC}. By using them, you can still access and visualize data produced with rel. 21, if you need that."
+        echo; echo -e "   ${RED}${BOLD}--->${NC} Please refer to the instructions published at: ${NC}${BOLD}${UNDERLINED} http://atlas-vp1.web.cern.ch/atlas-vp1/home/documentation/running-the-latest-vp1-version/${NC} ${RED}${BOLD}<---${NC}"; echo; echo
+        MUSTQUIT=1
+    fi
+fi
+
+if [ $MUSTQUIT -eq 1 ]; then
+    exit 1;
+fi
+
+
+
 
 #######################################
 ##       Init config variables       ##
@@ -93,7 +157,6 @@ FLAG_CAVERN=0
 FLAG_TOYDETECTOR=0
 FLAG_GEOMODELSTATS=0
 FLAG_EXTRAPOLATOR=0
-FLAG_SPACEPOINTS=0
 FLAG_NOEXTRAPOLATOR=0
 FLAG_FITTER=0
 FLAG_MC=0
@@ -102,7 +165,8 @@ FLAG_NOGUI=0
 FLAG_CGAL=0
 FLAG_NSW=0
 FLAG_SLHC=0
-FLAG_CUSTOMGEOMETRY=0
+#FLAG_CUSTOMGEOMETRY=0 # currently not used
+FLAG_ADVANCED_ANTIALIASING=0
 MULTINP_SRC=""
 MULTINP_CPY=""
 TRIGDEC=""
@@ -221,8 +285,6 @@ while [ $i -le $# ]; do
 	FLAG_TOYDETECTOR=1
     elif [ "x${arg}" == "x-geomodel-stats" ]; then
 	FLAG_GEOMODELSTATS=1
-    elif [ "x${arg}" == "x-spacepoints" ]; then
-	FLAG_SPACEPOINTS=1
     elif [ "x${arg}" == "x-extrapolator" ]; then
 	FLAG_EXTRAPOLATOR=1
     elif [ "x${arg}" == "x-noextrapolator" ]; then
@@ -240,8 +302,11 @@ while [ $i -le $# ]; do
     elif [ "x${arg}" == "x-slhc" ]; then
         echo "SLHC"
         FLAG_SLHC=1
-    elif [ "x${arg}" == "x-customgeom" ]; then
-        FLAG_CUSTOMGEOMETRY=1
+    #elif [ "x${arg}" == "x-customgeom" ]; then
+    #    FLAG_CUSTOMGEOMETRY=1
+    elif [ "x${arg}" == "x-advanced-aa" ]; then
+        FLAG_ADVANCED_ANTIALIASING=1
+        export VP1_ADVANCED_ANTIALIASING=1
     elif [ "x${arg}" == "x-mc" ]; then
 	FLAG_MC=1
     elif [ "x${arg}" == "x-multinp" ]; then
@@ -469,9 +534,6 @@ fi
 if [ "x$FLAG_NOID" == "x1" -a "x$FLAG_NOMUON" == "x1" -a "x$FLAG_EXTRAPOLATOR" == "x1" ]; then
     ERRORS="$ERRORS\nOptions -extrapolator can not be used when both -noid and -nomuon are specified"
 fi
-if [ "x$FLAG_NOID" == "x1" -a "x$FLAG_SPACEPOINTS" == "x1" ]; then
-    ERRORS="$ERRORS\nOptions -spacepoints can not be used when -noid is specified"
-fi
 
 if [ "x$FLAG_EXTRAPOLATOR" == "x1" -a "x$FLAG_NOEXTRAPOLATOR" == "x1" ]; then
     ERRORS="$ERRORS\nOptions -extrapolator and -noextrapolator are incompatible"
@@ -660,6 +722,8 @@ if [ "x$FLAG_HELP" != "x0" ]; then
     echo "  -slhc                        : Enable special configurations for SLHC studies."
     echo
     echo "  -customgeom                 : Enable a custom geometry."
+    echo
+    echo "  -advanced-aa                : Enable advanced anti-aliasing for crisper, higher-quality images. DOES NOT WORK ON LXPLUS MACHINES!!!"
     echo
     echo "  -test                       : Show the athena command instead of executing it."
     echo
@@ -892,10 +956,6 @@ if [ "x$FLAG_GEOMODELSTATS" != "x0" ]; then
     if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
     OPTS="${OPTS}vp1GeoModelStats=True"
 fi
-if [ "x$FLAG_SPACEPOINTS" != "x0" ]; then
-    if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
-    OPTS="${OPTS}vp1SpacePoints=True"
-fi
 if [ "x$FLAG_EXTRAPOLATOR" != "x0" ]; then
     if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
     OPTS="${OPTS}vp1Extrapolator=True"
@@ -910,7 +970,7 @@ if [ "x$FLAG_NOAUTOCONF" != "x0" ]; then
 fi
 if [ "x$FLAG_FITTER" != "x0" ]; then
     if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
-    OPTS="${OPTS}vp1Fitter=True"
+    ERRORS="$ERRORS\nOption -refit is not currently supported."    
 fi
 if [ "x$FLAG_FATRAS" != "x0" ]; then
     if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
@@ -924,10 +984,14 @@ if [ "x$FLAG_SLHC" != "x0" ]; then
     if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
     OPTS="${OPTS}vp1SLHC=True"
 fi
-if [ "x$FLAG_CUSTOMGEOMETRY" != "x0" ]; then
-    if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
-    OPTS="${OPTS}vp1CustomGeometry=True"
-fi
+#if [ "x$FLAG_CUSTOMGEOMETRY" != "x0" ]; then
+#    if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
+#    OPTS="${OPTS}vp1CustomGeometry=True"
+#fi
+#if [ "x$FLAG_ADVANCED_ANTIALIASING" != "x0" ]; then
+#    if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
+#    OPTS="${OPTS}vp1AdvancedAntialiasing=True"
+#fi
 if [ "x$FLAG_NOGUI" != "x0" ]; then
     if [ "x$OPTS" != "x" ]; then OPTS="$OPTS;"; fi
     OPTS="${OPTS}vp1NoGui=True"
